#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)

begin
  require "pry-byebug" if ENV["HIP_ENV"] == "debug"
rescue LoadError
  # do nothing
end

require "hip"
require "hip/cli"
require "hip/run_vars"

Signal.trap("INT") do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  Hip::CLI.start(ARGV)
rescue Hip::Error => e
  puts "ERROR: #{e.message}"
  exit 1
end
